# Automatically generated by configure - do not modify
SRC_PATH=/AFLplusplus/nyx_mode/QEMU-Nyx/roms/seabios
AS=as
CCAS=gcc-11
CC=gcc-11
BCC=bcc
CPP=gcc-11 -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
